### ISSUE TITLE
Cannot run program "protoc"

### ISSUE THREAD

**Issue by dtracers** [andrewkroh/gradle-protobuf-plugin#13]
Caused by: java.io.IOException: Cannot run program "protoc": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)

**Comment by andrewkroh** [comment]
The `protoc` compiler must be installed on the system. And it must be on the `PATH` or you can set the `compiler` option to point the the absolute path of the compiler.
